<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>JiaRemoteWin</RootNamespace>
    <AssemblyName>JiaRemoteWin</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>disable</Nullable>
    <StartupObject>JiaRemoteWin.App</StartupObject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>